version: "3.8"

services:
  app:
    build: .
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:byb202007leave@106.55.167.103:17017/db_test?authSource=admin
      - MONGODB_DB=hongguo_videos
    restart: unless-stopped
